import "dotenv/config";
import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import {
	MUIThemeProvider,
	StorePublicPosts,
	StoreUserData,
	StoreAllUsersData,
	// ReceiveMessage,
	// ReceiveNotification,
} from "./_components/client";
import { Container } from "@mui/material";
import "../globals.css";
import { ReduxProvider } from "@/redux/ReduxProvider";

export const metadata: Metadata = {
	title: "chatAlong - Discover and create your own journey",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<AppRouterCacheProvider>
					<MUIThemeProvider>
						<ReduxProvider>
							<main>
								<StoreUserData />
								<StorePublicPosts />
								<StoreAllUsersData />
								{/* <ReceiveNotification /> */}
								{/* <ReceiveMessage /> */}
								<Container
									maxWidth={"sm"}
									sx={{
										px: 0,
										pb: 7,
										overflow: "auto",
										height: "100vh",
										position: "relative",
										boxShadow: "0px 0px 2px 3px #00000021",
										overflowX: "hidden",
									}}
								>
									{children}
								</Container>
							</main>
						</ReduxProvider>
					</MUIThemeProvider>
				</AppRouterCacheProvider>
			</body>
		</html>
	);
}
