import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { MUIThemeProvider } from "./_components/client";
import { Container } from "@mui/material";
import { Footer, Header } from "@/shared";

export const metadata: Metadata = {
	title: "chatAlong - Discover and create your own journey",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<AppRouterCacheProvider>
					<MUIThemeProvider>
						<Container
							maxWidth={"sm"}
							sx={{
								height: "100vh",
								position: "relative",
								boxShadow: "0px 0px 2px 3px #00000021",
							}}
						>
							<Header />
							{children}
							<Footer />
						</Container>
					</MUIThemeProvider>
				</AppRouterCacheProvider>
			</body>
		</html>
	);
}
