import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { MUIThemeProvider } from "./_client-components";
import { Container } from "@mui/material";
import { Header } from "@/shared";

export const metadata: Metadata = {
	title: "chatAlong - Discover and create your own journey",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<AppRouterCacheProvider>
					<MUIThemeProvider>
						<Container maxWidth={"md"} sx={{ height: "100vh" }}>
							<Header />
							{children}
						</Container>
					</MUIThemeProvider>
				</AppRouterCacheProvider>
			</body>
		</html>
	);
}
